"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Run = { id: string; periodStart: string | null; periodEnd: string | null; sourceFilename: string; processedAt: string | null; createdAt: string; status: string; totalRecords: number; errorMessage: string | null; isCurrent: boolean };
const date = (value: string | null) => value ? new Date(value).toLocaleString("pt-BR") : "—";

export default function AdminPage() {
  const router = useRouter();
  const [runs, setRuns] = useState<Run[]>([]), [file, setFile] = useState<File | null>(null), [message, setMessage] = useState<string | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(false);
  const loadRuns = useCallback(async () => { const response = await fetch("/api/admin/runs"); if (response.status === 401 || response.status === 403) { router.replace("/"); return; } if (response.ok) setRuns((await response.json()).runs); }, [router]);
  useEffect(() => { void loadRuns(); }, [loadRuns]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!file) return; setLoading(true); setMessage(null); setError(null); const body = new FormData(); body.set("file", file); try { const response = await fetch("/api/admin/report", { method: "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Falha no processamento."); setMessage(`Processamento concluído: ${result.totalRecords} registros, período ${result.periodStart} a ${result.periodEnd}.`); setFile(null); await loadRuns(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha no processamento."); } finally { setLoading(false); } }
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">Administração</p><h1>Atualizar relatório</h1><p>O PDF será processado temporariamente e os dados serão gravados no PostgreSQL privado.</p></div><button type="button" onClick={() => router.push("/")}>Voltar ao dashboard</button></header><section className="admin-card"><h2>Enviar PDF</h2><form onSubmit={submit}><label htmlFor="report-file">Arquivo PDF</label><input id="report-file" type="file" accept="application/pdf,.pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} required /><small>Limite padrão: 25 MB. O arquivo não fica público.</small>{message && <div className="admin-success">{message}</div>}{error && <div className="login-error">{error}</div>}<button type="submit" disabled={loading || !file}>{loading ? "Processando…" : "Processar e atualizar"}</button></form></section><section className="admin-card"><div className="admin-section-title"><h2>Histórico de atualizações</h2><button type="button" onClick={() => void loadRuns()}>Atualizar lista</button></div><div className="admin-table-wrap"><table><thead><tr><th>Data/hora</th><th>Período</th><th>Arquivo</th><th>Registros</th><th>Status</th><th>Erro</th><th>Excel</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{date(run.processedAt || run.createdAt)}</td><td>{run.periodStart ? `${date(run.periodStart)} a ${date(run.periodEnd)}` : "—"}</td><td>{run.sourceFilename}</td><td>{run.totalRecords}</td><td><span className={`run-status run-${run.status.toLowerCase()}`}>{run.status}{run.isCurrent ? " · atual" : ""}</span></td><td>{run.errorMessage || "—"}</td><td>{run.status === "SUCCESS" && <a href={`/api/admin/excel/${run.id}`}>Baixar</a>}</td></tr>)}</tbody></table></div></section></main>;
}
